<?php

/***************************************************************************
 *    Title: xphpBBi - phpBB Complete Integration project
 *    Description: Project to turn the phpBB forums into a fully functioning
 *        Xoops2 Module. Based on the phpBB 2.0.9 port from BBpixel.com -
 *        (PBBoard v1.22).
 *    Credits: Xoops2 Module Development Team - Koudanshi - phpBB Group
 *    Thanks: To Koudanshi for a great start in his port, and phpBB Group for
 *        such a great forum software.
 *    License: GNU/GPL version 2 or later.
 ****************************************************************************/

$modversion['name'] = BBOARD_NAME;
$modversion['version'] = '0.8';
$modversion['description'] = BBOARD_DESC;
$modversion['credits'] = 'Based on BBPixel\'s port of phpBB 2.0.9<br>phpBB 2.0.9 is a product of phpBB Group';
$modversion['author'] = 'XOOPS 2 Module Dev Team - phpBB Complete Integration Project';
$modversion['help'] = 'None';
$modversion['license'] = 'GNU/GPL';
$modversion['official'] = 0;
$modversion['image'] = './images/logo.gif';
$modversion['dirname'] = 'xphpbbi';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Run Script After Installation
$modversion['onInstall'] = 'includes/installscript.php';

// Run Script After Uninstallation
$modversion['onUninstall'] = 'includes/uninstallscript.php';

//---------------------------------------------
// Tables created by sql file (without prefix!)
//---------------------------------------------
$modversion['tables'][1] = 'phpbbi_auth_access';
$modversion['tables'][2] = 'phpbbi_user_ext';
$modversion['tables'][3] = 'phpbbi_session_ext';
$modversion['tables'][4] = 'phpbbi_banlist';
$modversion['tables'][5] = 'phpbbi_categories';
$modversion['tables'][6] = 'phpbbi_config';
$modversion['tables'][7] = 'phpbbi_confirm';
$modversion['tables'][8] = 'phpbbi_disallow';
$modversion['tables'][9] = 'phpbbi_forum_prune';
$modversion['tables'][10] = 'phpbbi_forums';
$modversion['tables'][11] = 'phpbbi_posts';
$modversion['tables'][12] = 'phpbbi_posts_text';
$modversion['tables'][13] = 'phpbbi_privmsgs';
$modversion['tables'][14] = 'phpbbi_privmsgs_text';
$modversion['tables'][15] = 'phpbbi_search_results';
$modversion['tables'][16] = 'phpbbi_search_wordlist';
$modversion['tables'][17] = 'phpbbi_search_wordmatch';
$modversion['tables'][18] = 'phpbbi_themes';
$modversion['tables'][19] = 'phpbbi_themes_name';
$modversion['tables'][20] = 'phpbbi_topics';
$modversion['tables'][21] = 'phpbbi_topics_watch';
$modversion['tables'][22] = 'phpbbi_vote_desc';
$modversion['tables'][23] = 'phpbbi_vote_results';
$modversion['tables'][24] = 'phpbbi_vote_voters';
$modversion['tables'][25] = 'phpbbi_words';

//--------------
// Admin things
//--------------
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'index.php';
$modversion['adminmenu'] = 'menu.php';

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'search.inc.php';
$modversion['search']['func'] = 'xphpbbi_search';

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = 'Faq';
$modversion['sub'][1]['url'] = 'faq.php';
$modversion['sub'][2]['name'] = 'Search';
$modversion['sub'][2]['url'] = 'search.php';

// Blocks
$modversion['blocks'][1]['file'] = 'xphpbbi.php';
$modversion['blocks'][1]['name'] = BBOARD_BNAME1;
$modversion['blocks'][1]['description'] = 'Shows recent topics in the forums';
$modversion['blocks'][1]['show_func'] = 'xphpbbi_show';
$modversion['blocks'][1]['options'] = '10|1|time';
$modversion['blocks'][1]['edit_func'] = 'xphpbbi_edit';
$modversion['blocks'][1]['template'] = 'xphpbbi_block_new.html';

$modversion['blocks'][2]['file'] = 'xphpbbi.php';
$modversion['blocks'][2]['name'] = BBOARD_BNAME2;
$modversion['blocks'][2]['description'] = 'Shows most viewed topics in the forums';
$modversion['blocks'][2]['show_func'] = 'xphpbbi_show';
$modversion['blocks'][2]['options'] = '10|1|views';
$modversion['blocks'][2]['edit_func'] = 'xphpbbi_edit';
$modversion['blocks'][2]['template'] = 'xphpbbi_block_top.html';

$modversion['blocks'][3]['file'] = 'xphpbbi.php';
$modversion['blocks'][3]['name'] = BBOARD_BNAME3;
$modversion['blocks'][3]['description'] = 'Shows most active topics in the forums';
$modversion['blocks'][3]['show_func'] = 'xphpbbi_show';
$modversion['blocks'][3]['options'] = '10|1|replies';
$modversion['blocks'][3]['edit_func'] = 'xphpbbi_edit';
$modversion['blocks'][3]['template'] = 'xphpbbi_block_active.html';

// Smarty
$modversion['use_smarty'] = 1;
